### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by Kickball** [JeremyAkita09/Webdata1#1]
Hey Jeremy,

I stumbled upon this through reddit. I just thought I'd drop you a note, because I'm having a hard time understanding this project. There is little documentation, both with the code and with the project as a whole.

If you want this project to be better documented, and in turn get a bit more traction I would recommend:

- [ ] Update readme.md with a description of what the program is designed to accomplish (goal).
- [ ] Update readme.md with a list of services that this program can scrape.
- [ ] Update readme.md with a list of the parameters or a description of the way the program is used. (inputs/outputs, parameters, etc)
- [ ] Update readme.md with a list of steps required to get the program running (Including dependencies).

Kind regards,
Ed

**Comment by JeremyAkita09** [comment]
Dear Ed
I am making improvments on the Readme.md document 
your sincerely
Jeremy

**Comment by JeremyAkita09** [comment]
I have made Some changes to  the Readme 
and tell me what you think of Readme.doc

**Comment by Kickball** [comment]
Your changes were a good start, please see #2 for my updates.

**Comment by JeremyAkita09** [comment]
i made some improvements on readme.doc but i would like to make more change if thats okay with you ?

**Comment by Kickball** [comment]
Yeah go ahead :smile:

**Comment by JeremyAkita09** [comment]
have you ever look at java files ?

**Comment by Kickball** [comment]
Nope, but I've worked with C# before. Btw you should probably add file extensions to the main project files.
